// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KafkaMessageDataObj.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发送kafka数据格式
type KafkaMessageData struct {
	Datatype             string   `protobuf:"bytes,1,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition            int64    `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KafkaMessageData) Reset()         { *m = KafkaMessageData{} }
func (m *KafkaMessageData) String() string { return proto.CompactTextString(m) }
func (*KafkaMessageData) ProtoMessage()    {}
func (*KafkaMessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_686e631736da0704, []int{0}
}

func (m *KafkaMessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessageData.Unmarshal(m, b)
}
func (m *KafkaMessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessageData.Marshal(b, m, deterministic)
}
func (m *KafkaMessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessageData.Merge(m, src)
}
func (m *KafkaMessageData) XXX_Size() int {
	return xxx_messageInfo_KafkaMessageData.Size(m)
}
func (m *KafkaMessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessageData.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessageData proto.InternalMessageInfo

func (m *KafkaMessageData) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *KafkaMessageData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KafkaMessageData) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *KafkaMessageData) GetPartition() int64 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func init() {
	proto.RegisterType((*KafkaMessageData)(nil), "protobuf.KafkaMessageData")
}

func init() { proto.RegisterFile("KafkaMessageDataObj.proto", fileDescriptor_686e631736da0704) }

var fileDescriptor_686e631736da0704 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xf4, 0x4e, 0x4c, 0xcb,
	0x4e, 0xf4, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x75, 0x49, 0x2c, 0x49, 0xf4, 0x4f, 0xca, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x65, 0x5c, 0x02,
	0xe8, 0xca, 0x84, 0xa4, 0xb8, 0x38, 0x52, 0x12, 0x4b, 0x12, 0x4b, 0x2a, 0x0b, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x21, 0x2e, 0x16, 0x10, 0x5b, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x27, 0x08, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2f, 0xc8, 0x4c, 0x96, 0x60,
	0x06, 0x2b, 0x86, 0x70, 0x84, 0x64, 0xb8, 0x38, 0x0b, 0x12, 0x8b, 0x4a, 0x32, 0x4b, 0x32, 0xf3,
	0xf3, 0x24, 0x58, 0x14, 0x18, 0x35, 0x98, 0x83, 0x10, 0x02, 0x49, 0x6c, 0x60, 0x17, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9e, 0x6b, 0xd7, 0xa5, 0x00, 0x00, 0x00,
}
